### ISSUE TITLE
Great Code Just One Question

### ISSUE THREAD

**Issue by ghost** [floreks/AES#3]
I love your code, I've been reading it and it all makes sense for the most part. Something that was however throwing me off is where are you using a private key for the encryption? Otherwise great work and I look forward to see what else you produce :)

**Comment by floreks** [comment]
Thanks :)

AES is a symmetric encryption standard so the same key is used to encrypt/decrypt the data. Key is defined as a vector of bytes in the beginning of `cipher.cpp`.
